language: python

python:
  - 3.6

cache: pip

install:
  - pip install --upgrade pip
  - git clone https://github.com/thu-coai/cotk.git && cd cotk && pip install -e .[develop] --progress-bar off
  - pip install sphinx==1.8.5
  - pip install m2r

script:
  - pytest test_seq2seq_pytorch.py

deploy:
  - provider: script
    skip-cleanup: true
    script: coveralls
    on:
      all_branches: true
      condition: true
